const mockRepos = {
  'sparky-js-with-a-very-long-name': { id: 0, name: 'sparky-js-with-a-very-long-name', watchers: 13 },
  'web-init': { id: 1, name: 'web-init', watchers: 26 },
  'astha.me': { id: 2, name: 'astha.me', watchers: 39 },
  code: { id: 3, name: 'code', watchers: 52 },
  slingshop: { id: 4, name: 'slingshop', watchers: 65 },
  'sraj.me': { id: 5, name: 'sraj.me', watchers: 78 },
  'Testgen-web': { id: 6, name: 'Testgen-web', watchers: 91 },
  'gmr-backend': { id: 7, name: 'gmr-backend', watchers: 104 },
  'gmr-app': { id: 8, name: 'gmr-app', watchers: 117 },
  slack: { id: 9, name: 'slack', watchers: 130 },
  'Angualar-Services': { id: 10, name: 'Angualar-Services', watchers: 143 },
  dipper: { id: 11, name: 'dipper', watchers: 156 },
  fixed_sidebar: { id: 12, name: 'fixed_sidebar', watchers: 169 },
  'dipper-cart': { id: 13, name: 'dipper-cart', watchers: 182 },
  'Angular-elements': { id: 14, name: 'Angular-elements', watchers: 195 },
  widgets: { id: 15, name: 'widgets', watchers: 208 },
  DipperAssignment: { id: 16, name: 'DipperAssignment', watchers: 221 },
  assignment2: { id: 17, name: 'assignment2', watchers: 234 },
  formvalidation: { id: 18, name: 'formvalidation', watchers: 247 },
  autocomplete: { id: 19, name: 'autocomplete', watchers: 260 },
  quotegen: { id: 20, name: 'quotegen', watchers: 273 },
  calculator: { id: 21, name: 'calculator', watchers: 286 },
  Promodoro: { id: 22, name: 'Promodoro', watchers: 299 },
  Gamezop: { id: 23, name: 'Gamezop', watchers: 312 },
  'ng-view': { id: 24, name: 'ng-view', watchers: 325 },
  'ng-hs': { id: 25, name: 'ng-hs', watchers: 338 },
  'to-do': { id: 26, name: 'to-do', watchers: 351 },
  odot: { id: 27, name: 'odot', watchers: 364 },
  treebook: { id: 28, name: 'treebook', watchers: 377 },
  Products: { id: 29, name: 'Products', watchers: 390 },
  Collegedunia: { id: 30, name: 'Collegedunia', watchers: 403 },
  'local-weather': { id: 31, name: 'local-weather', watchers: 416 },
  wiki: { id: 32, name: 'wiki', watchers: 429 },
  ollert: { id: 33, name: 'ollert', watchers: 442 },
  rust: { id: 34, name: 'rust', watchers: 455 },
  'github-notetaker': { id: 35, name: 'github-notetaker', watchers: 468 },
  podcast: { id: 36, name: 'podcast', watchers: 481 },
  graph: { id: 37, name: 'graph', watchers: 494 },
  correlation: { id: 38, name: 'correlation', watchers: 507 },
  hyper: { id: 39, name: 'hyper', watchers: 520 },
  babel: { id: 40, name: 'babel', watchers: 533 },
  website: { id: 41, name: 'website', watchers: 546 },
  'podcst-web': { id: 42, name: 'podcst-web', watchers: 559 },
  'React-todo-list': { id: 43, name: 'React-todo-list', watchers: 572 },
  assignment: { id: 44, name: 'assignment', watchers: 585 },
  'react-webpack-demo': { id: 45, name: 'react-webpack-demo', watchers: 598 },
  'es6-todomvc': { id: 46, name: 'es6-todomvc', watchers: 611 },
  'react-boilerplate': { id: 47, name: 'react-boilerplate', watchers: 624 },
  'form-react': { id: 48, name: 'form-react', watchers: 637 },
  'twitter-trends': { id: 49, name: 'twitter-trends', watchers: 650 },
  figs: { id: 50, name: 'figs', watchers: 663 },
  'react-auto-header-list': { id: 51, name: 'react-auto-header-list', watchers: 676 }
};

export default {
  searchTerm: '',
  repos: mockRepos || {},
  selectedOrg: 'facebook',
  selectedRepo: '',
  errorMessage: '',
};
